In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.6.0+cu124'

## Introduction to tensors
### Creating tensors


In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()


7

In [ ]:
scalar.shape # no shape

torch.Size([])

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim # count square brackets in the beginning (= '[')

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3,4],
                        [3,6,9,6],
                        [2,4,5,2]],
                       [[12,13,1,24],
                        [23,2,4,1],
                        [1,2,3,1]]])

TENSOR

tensor([[[ 1,  2,  3,  4],
         [ 3,  6,  9,  6],
         [ 2,  4,  5,  2]],

        [[12, 13,  1, 24],
         [23,  2,  4,  1],
         [ 1,  2,  3,  1]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 4])

### Random tensors

Why random tensors?
Random tensors are important because the way many neural nteworks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent hte data!
`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`


In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7638, 0.9027, 0.7727, 0.2117],
        [0.0340, 0.7392, 0.6839, 0.4253],
        [0.6549, 0.7227, 0.4722, 0.1236]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape t oan image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

### Zeros and ones


In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Creatomg a range of tensors and tensors-like

In [ ]:
# Use torch.arange, not deprecated
one_to_ten = torch.arange(1,11,1) # start, end, step (default 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors with PyTorch:
1. wrong datatype
2. wrong shape
3. wrong device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32, # what data type is the tensor (float32 etc)
                               device=None, # what device is the tensor on
                               requires_grad=False) # whether or not to track gradients with the tensor's operations

float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
new_tensor = float_16_tensor * float_32_tensor
new_tensor.dtype

torch.float32

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. wrong datatype - `tensor.dtype`
2. wrong shape - `tensor.shape`
3. wrong device - `tensor.device`



In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7548, 0.0705, 0.6002, 0.6231],
        [0.5663, 0.3237, 0.3112, 0.8778],
        [0.1628, 0.3522, 0.4592, 0.1233]])

In [ ]:
# Find out details
print(some_tensor)
print(f"Datatype is {some_tensor.dtype}")
print(f"Shape is {some_tensor.shape}")
print(f"Device tensor is on {some_tensor.device}")

tensor([[0.7548, 0.0705, 0.6002, 0.6231],
        [0.5663, 0.3237, 0.3112, 0.8778],
        [0.1628, 0.3522, 0.4592, 0.1233]])
Datatype is torch.float32
Shape is torch.Size([3, 4])
Device tensor is on cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication


In [ ]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch inbuilt functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways performing multiplication in neural neutworks and deeep learning
1. element-wise
2. matrix (dot product)

In [ ]:
# Element-wise
print(tensor, "*", tensor)
print(f"equals {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals tensor([1, 4, 9])


In [ ]:
# Matrix multiiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 851 µs, sys: 0 ns, total: 851 µs
Wall time: 936 µs


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 272 µs, sys: 45 µs, total: 317 µs
Wall time: 255 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [ ]:
#torch.matmul(torch.rand(2,3), torch.rand(2,3))
torch.matmul(torch.rand(2,3), torch.rand(3,4))

tensor([[0.4365, 0.8821, 0.1316, 0.4009],
        [0.6247, 1.6586, 0.8640, 0.7114]])

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7, 8],
                         [9,10],
                         [11,12]])
# transpose is .T
torch.mm(tensor_A, tensor_B.T) # mm = matmul !!

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

## Finding the min, max, mean etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean - note: dtype of float32 needed
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding the positional min and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the position in tensor that has the minimum value with argmin()
# --> returns index position of the min value
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
# Find the max index
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing... tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Create a tensor
import torch

x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (as a view of a tensor shares THE SAME memory)
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze() - remove all single dimensions from a tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove dimensions
x_squeezed = x_reshaped.squeeze()

print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a tensor
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a target in specified order
x_original = torch.rand(size=(224,224,3)) # height, width, color channel

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_permuted

tensor([[[0.1982, 0.6432, 0.1369,  ..., 0.0651, 0.8071, 0.5128],
         [0.2293, 0.8226, 0.9476,  ..., 0.7548, 0.6359, 0.6563],
         [0.3146, 0.4181, 0.0658,  ..., 0.1915, 0.3323, 0.5354],
         ...,
         [0.6463, 0.0124, 0.6358,  ..., 0.2066, 0.6886, 0.8185],
         [0.7761, 0.9189, 0.3867,  ..., 0.3911, 0.4864, 0.8219],
         [0.0888, 0.7046, 0.9613,  ..., 0.9756, 0.1313, 0.3557]],

        [[0.5886, 0.6462, 0.9025,  ..., 0.1649, 0.6622, 0.7892],
         [0.5009, 0.2537, 0.9185,  ..., 0.2194, 0.6849, 0.0186],
         [0.3204, 0.7820, 0.8836,  ..., 0.8106, 0.7167, 0.4423],
         ...,
         [0.3908, 0.5313, 0.9755,  ..., 0.7012, 0.9042, 0.6971],
         [0.1009, 0.8844, 0.8730,  ..., 0.6179, 0.4742, 0.5690],
         [0.5587, 0.3249, 0.7872,  ..., 0.9501, 0.7549, 0.5579]],

        [[0.1909, 0.3503, 0.3511,  ..., 0.6250, 0.1241, 0.3076],
         [0.1480, 0.0553, 0.6709,  ..., 0.7597, 0.8476, 0.4378],
         [0.2580, 0.9438, 0.9438,  ..., 0.8080, 0.9675, 0.

In [ ]:
x_original[1,0,0] = 99999
x_permuted[1,0,0]

tensor(0.5886)

## Indexing (selecting data from tensors)

Similar to NumPy



In [ ]:
# create tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# let's index!
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# middle, 2 ways!
x[0,0]
x[0][0]

tensor([1, 2, 3])

In [ ]:
# last dimension
x[0][0][0]
x[0,2,2]

tensor(9)

In [ ]:
# ':' gets all!
x[0,:,2]

tensor([3, 6, 9])

## PyTorch tensors & NumPy

Possibility to interact with NumPy

* Data from NumPy to PyTorch tensor `torch.from_numpy(ndarray)`
* PyTorch to NumPy `torch.Tensor.numpy()`

In [4]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # warning: numpy --> pytorch, pytorch reflects numpy's default datatype of float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [5]:
tensor.dtype

torch.float64

In [6]:
array.dtype

dtype('float64')

In [7]:
array = array + 1
array, tensor
# note, only array changes

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [8]:
# tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [9]:
# change the tewnsor, how about the change now?
tensor = tensor + 1
tensor, numpy_tensor
# --> again, only another one changes

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

Shortly, how a neural network learns:
`random numbers --> tensor operations --> update random numbers to be better --> repeat...`

To reduce randomness in NN's and PyTorch, we use **random seed**.

Essentially, we "flavour" the randomness.

In [28]:
import torch

# Create 2 random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7019, 0.1722, 0.6267, 0.0363],
        [0.2349, 0.7476, 0.5806, 0.2413],
        [0.9670, 0.8145, 0.3860, 0.9492]])
tensor([[0.4492, 0.5966, 0.0813, 0.3660],
        [0.5571, 0.3584, 0.8244, 0.6825],
        [0.5429, 0.9759, 0.4180, 0.2091]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [43]:
# Let's make reandom, reproducible ones!
import torch

# set the seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster things)

GPUs = faster computation of numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes better

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU
2. Use own GPU - takes a bit of setup and investement of purchasing GPU but lots of options
3. Use cloud computing - GCP, AWS, Azure, you can rent computers on the cloud for use!

For 2, 3 PyTorch + GPU drivers (CUDA) takes a bit of settipng up, check PyTorch's setup documentation!

In [44]:
!nvidia-smi

Mon Jun  2 21:16:51 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   37C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU access with PyTorch

In [45]:
import torch
torch.cuda.is_available() # check for GPU access possibiility

True

For PyTorch, we setup device agnostic code:

In [46]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [47]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

Why? We get faster computations!

In [48]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [49]:
# Move to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [50]:
# If tensor is on GPU, can't transform to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [52]:
# To fix, first set it to the CPU
tensor_back_GPU = tensor_on_gpu.cpu().numpy()
tensor_back_GPU

array([1, 2, 3])